### ISSUE TITLE
?tile recolor command uses different colors for k

### ISSUE THREAD

**Issue by HeladoDeBrownie** [TrashMonks/cryptogull#18]
depending on whether it's the detail or main color, k renders differently. theoretically they should both be qud viridian

**Comment by egocarib** [comment]
This appears to have been fixed somewhere along the way. We've refactored how color works a few times, so I'm guessing it was spontaneously addressed at some point.

![image](https://user-images.githubusercontent.com/3429497/107689109-0d48a880-6c6e-11eb-8c36-db533fa9c943.png)
