### ISSUE TITLE
Feature Request: Single Page Search

### ISSUE THREAD

**Issue by egocarib** [TrashMonks/cryptogull#28]
A common use case for `?wiki <term>` is to direct someone to a specific wiki page. In those situations, it'd be nice to avoid having a full list of 10 related search results. Would be nice to have a method to attempt an exact page name search and just display that one result. Perhaps when someone encloses their term in double quotes or perhaps as a different command, like `?wikipage Jacked` to have crypto only return that one page.

**Comment by HeladoDeBrownie** [comment]
i am willing to take this if no one objects

**Comment by egocarib** [comment]
Fixed by HeladoDeBrownie in commit 70098789f5efb90b40aec7933e45d7eb64be1644.

Further expansion on this concept has been implemented in pull request https://github.com/TrashMonks/cryptogull/pull/37

Closing this issue.
