### ISSUE TITLE
Not parsing Psionic Migraines (character code 'OW') properly

### ISSUE THREAD

**Issue by ripasso** [TrashMonks/cryptogull#29]
Example, using a valid code generated in-game: https://cavesofqud.gamepedia.com/Special:RunQuery/Cryptogull?pfRunQueryFormName=Cryptogull&Cryptogull%5Bcode%5D=BAMKJMLNDYDXD1DZOW

There should be an entry for Psionic Migraines at the end of that list. Discord bot has the same issue.

**Comment by syntaxaire** [comment]
Thanks for the report! We were being restrictive with the regular expression filter and when the Psionic Migraines defect was added, they used the code "OW" (heh) which didn't match the existing pattern. Upgraded to be more permissive of this and other future mutation codes.
