### ISSUE TITLE
add ?pronouns command

### ISSUE THREAD

**Issue by HeladoDeBrownie** [TrashMonks/cryptogull#33]
a command to list a character's pronouns. `?pronouns Q Girl` or similar would return she/her, or possibly even fully decline the pronoun set

**Comment by syntaxaire** [comment]
Looking into this. It needs a bit of backend work since some creatures have a pronouns tag but others have only a gender tag.

**Comment by egocarib** [comment]
Appears to have been addressed by 932a6bba2607383eb3747e7db81646efe8c29114, however I will defer to @syntaxaire to close this issue, in case there are still outstanding details planned to be implemented.

**Comment by syntaxaire** [comment]
Forgot to close this!
