### ISSUE TITLE
Option for One-Word Sleeptalk

### ISSUE THREAD

**Issue by egocarib** [TrashMonks/cryptogull#60]
Suggestion: if someone submits a `?sleeptalk` command with only one word (such as `?sleeptalk spindle`), crypto could randomly choose from among the possible markov two-word combos and form a sleeptalk sentence from it, instead of listing them out and requiring the user to re-submit a new request. Might make it a little easier to use the command without knowing specific word combos in the corpus. Also seems like it could yield more variety/surprise in the output.

If we still want to allow folks to see the two-word combos, we could consider adding a secondary command, like `?sleeptalk [<word-in-brackets>]` or `?sleeptalk options <word>` or similar.

**Comment by egocarib** [comment]
Oh, I just realized you can use `?sleeptalk` with no argument at all. How did I miss that. 😄

I would say this suggestion is probably still valid but not as important IMO since there's already a nice, easy way to use the command.

**Comment by Wreckstation** [comment]
e9322bf also case insensitive and ignore punctuation
