### ISSUE TITLE
?tile command: search on display name

### ISSUE THREAD

**Issue by HeladoDeBrownie** [TrashMonks/cryptogull#8]
most players aren't going to be familiar with the internal ids of creatures, so it makes sense to let them input a display name, e.g., `?tile sheba`.

some considerations:

- some display names are ambiguous. but, some ambiguous display names have a *tile* that's *un*ambiguous. in those cases, it makes sense to display that tile despite the ambiguity. dromad traders come to mind.
- some display names map to the same internal id, *but* have a consistent tile and coloration per display name. stat saps come to mind.
- while we *could* have a separate command that gives the id from the display name, this not only creates an extra step and channel noise, but loses information (see last point).

**Comment by syntaxaire** [comment]
This was implemented with b2ad5d01.
